packages:
  - "apps/*"
  - "packages/*/*"

# Monorepo structure:
# - apps/StratonHub: StratonHub documentation site
# - apps/boardroom: The Apex (Executive Board Decision Engine MVP)
# - packages/TailwindCSS-V4/Design-System: Axis Visual Canon design system
# - packages/TypeScript/Shared-Types: Shared TypeScript types and Zod schemas
# - packages/NextJS/Shared-Utils: Shared utility functions
# - packages/NextJS/Domain-Core: Next.js domain patterns
# - packages/NodeJS/Monitoring: Node.js monitoring utilities
# - packages/NodeJS/Performance: Node.js performance utilities
# - packages/Monorepo/Config: Shared configuration (TypeScript, Tailwind, etc.)
# - packages/Monorepo/Templates: Project templates and schemas
